# Generated by Django 3.2.13 on 2022-05-04 23:30

from django.db import migrations


def add_organization(apps, schema_editor):
    Organization = apps.get_model('kudos', 'Organization')

    o = Organization(name='SomeCorp')
    o.save()



class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_organization)
    ]
